language: python
python:
  - "3.4"
cache: pip
sudo: false

install:
  - pip install -r requirements.txt

before_script:
  - "python manage.py makemigrations"
  - "python manage.py migrate"

script:
  -   py.test