language: python
python:
  - "3.4"
cache: pip
sudo: false

install:
  - pip install -r requirements.txt
  - pip install tox pytest-cov coveralls

before_script:
  - "python manage.py makemigrations"
  - "python manage.py migrate"

script:
  - py.test --cov
  - tox

after_success:
    - coveralls
    - CODECLIMATE_REPO_TOKEN=7f36a040275edf80bb954dda2025f501da1cb8668e4a24c047bedc546db6d56a